---
- name: check for variables
  stat:
    path: "{{ role_path }}/vars/{{ vm_type }}.yml"
  register: stat_result

- name: import variables
  include_vars:
    file: "{{ role_path }}/vars/{{ vm_type }}.yml"
  when: stat_result.stat.exists|bool == true

- name: clone VM
  vmware_guest:
    hostname: "{{ vc_host }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    validate_certs: "{{ vc_validate_certs }}"
    datacenter: "{{ vc_datacenter }}"
    cluster: "{{ vc_cluster }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    annotation: "{{ vm_annotation }}"
    wait_for_ip_address: "{{ vm_wait_for_ip_address }}"
    customvalues: "{{ vm_customvalues }}"
    networks: "{{ vm_networks }}"
    disk: "{{ vm_disk }}"
    hardware: "{{vm_hardware}}"
    customization: "{{ vm_customization }}"
